# Generated by Django 5.1.15 on 2026-03-04 01:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFamilyVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='families.family')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desire_rating', models.PositiveSmallIntegerField(help_text='1 = Nice to have, 5 = Really want this!', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('purchase_link', models.URLField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='wishlist/')),
                ('is_soft_removed', models.BooleanField(default=False)),
                ('soft_remove_reason', models.CharField(blank=True, choices=[('no_longer_wanted', 'No longer wanted'), ('already_have', 'Already have this / received as a gift')], default='', max_length=20)),
                ('soft_removed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
                ('visible_to_families', models.ManyToManyField(blank=True, related_name='visible_items', through='wishlist.ItemFamilyVisibility', to='families.family')),
            ],
            options={
                'ordering': ['-desire_rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchasedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('purchased_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_made', to=settings.AUTH_USER_MODEL)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_record', to='wishlist.wishlistitem')),
            ],
        ),
        migrations.AddField(
            model_name='itemfamilyvisibility',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishlist.wishlistitem'),
        ),
        migrations.AlterUniqueTogether(
            name='itemfamilyvisibility',
            unique_together={('item', 'family')},
        ),
    ]
