# Generated by Django 5.1.15 on 2026-03-07 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_relationship',
            field=models.CharField(blank=True, choices=[('child', 'Child'), ('elder', 'Elder'), ('other', 'Other')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='is_managed',
            field=models.BooleanField(default=False),
        ),
    ]
