# Generated by Django 5.1.15 on 2026-03-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyinvitation',
            name='role',
            field=models.CharField(choices=[('admin', 'Family Admin'), ('member', 'Member')], default='member', max_length=10),
        ),
    ]
