# Generated by Django 5.1.15 on 2026-05-30 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('state', models.CharField(help_text='2-letter state code for tax estimates', max_length=2)),
                ('filing_status', models.CharField(choices=[('single', 'Single'), ('married_jointly', 'Married Filing Jointly'), ('married_separately', 'Married Filing Separately'), ('head_of_household', 'Head of Household')], default='single', max_length=30)),
                ('risk_tolerance', models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], default='moderate', max_length=20)),
                ('annual_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('income_growth_rate', models.DecimalField(decimal_places=2, default=3.0, help_text='Expected annual raise %, e.g. 3.0', max_digits=5)),
                ('target_retirement_age', models.PositiveSmallIntegerField(default=65)),
                ('income_end_age', models.PositiveSmallIntegerField(default=65, help_text='Age at which primary income stops (usually = retirement age)')),
                ('life_expectancy_age', models.PositiveSmallIntegerField(default=90)),
                ('is_setup_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='SpouseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('annual_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('income_growth_rate', models.DecimalField(decimal_places=2, default=3.0, help_text='Expected annual raise %, e.g. 3.0', max_digits=5)),
                ('target_retirement_age', models.PositiveSmallIntegerField(default=65)),
                ('income_end_age', models.PositiveSmallIntegerField(default=65)),
                ('life_expectancy_age', models.PositiveSmallIntegerField(default=90)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spouse', to='profiles.userprofile')),
            ],
            options={
                'verbose_name': 'Spouse Profile',
            },
        ),
    ]
