# Generated by Django 5.1.15 on 2026-05-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spouseprofile',
            name='income_end_age',
        ),
        migrations.RemoveField(
            model_name='spouseprofile',
            name='target_retirement_age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='income_end_age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='risk_tolerance',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='target_retirement_age',
        ),
        migrations.AlterField(
            model_name='spouseprofile',
            name='income_growth_rate',
            field=models.DecimalField(decimal_places=1, default=3.0, help_text='Expected annual raise %, e.g. 3.0', max_digits=4),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='income_growth_rate',
            field=models.DecimalField(decimal_places=1, default=3.0, help_text='Expected annual raise %, e.g. 3.0', max_digits=4),
        ),
    ]
