# Generated by Django 5.1.15 on 2026-05-30 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_income_source_and_remove_pension_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(choices=[('self', 'Primary User'), ('spouse', 'Spouse')], default='self', max_length=10)),
                ('name', models.CharField(help_text="e.g. 'Tom's Pension', 'Rental — 123 Main St'", max_length=200)),
                ('source_type', models.CharField(choices=[('social_security', 'Social Security'), ('pension', 'Pension'), ('annuity', 'Annuity'), ('iul', 'Indexed Universal Life (IUL)'), ('rental', 'Rental Property'), ('business', 'Business / Royalty'), ('part_time', 'Part-Time Work'), ('other', 'Other Income')], max_length=20)),
                ('ss_monthly_at_62', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly SS benefit if claimed at 62 (from SSA statement)', max_digits=8, null=True)),
                ('ss_monthly_at_67', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly SS benefit at Full Retirement Age / 67', max_digits=8, null=True)),
                ('ss_monthly_at_70', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly SS benefit if claimed at 70', max_digits=8, null=True)),
                ('ss_cola_rate', models.DecimalField(decimal_places=2, default=2.5, help_text='Annual SS COLA %, default 2.5%', max_digits=4)),
                ('annual_amount', models.DecimalField(decimal_places=2, default=0, help_text="Annual payout in today's dollars (not used for Social Security)", max_digits=12)),
                ('start_age', models.PositiveSmallIntegerField(default=65, help_text='Age at which this income begins')),
                ('end_age', models.PositiveSmallIntegerField(blank=True, help_text='Age at which income ends; blank = lifetime / until plan end', null=True)),
                ('is_inflation_adjusted', models.BooleanField(default=False, help_text='True = amount grows annually with inflation')),
                ('inflation_rate_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override inflation %; blank = use scenario inflation rate', max_digits=4, null=True)),
                ('is_taxable', models.BooleanField(default=True, help_text='False = tax-free (e.g. Roth, IUL distributions, HSA medical)')),
                ('tax_rate_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override tax rate %; blank = use scenario retirement tax rate', max_digits=5, null=True)),
                ('survivor_benefit_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Pension survivor benefit % paid to spouse after owner dies (pension only)', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_sources', to='profiles.userprofile')),
            ],
            options={
                'verbose_name': 'Income Source',
                'ordering': ['source_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(choices=[('self', 'Primary User'), ('spouse', 'Spouse')], default='self', max_length=10)),
                ('name', models.CharField(help_text="e.g. 'Tom's 401k at Fidelity'", max_length=200)),
                ('account_type', models.CharField(choices=[('401k', '401(k) — Pre-Tax'), ('roth_401k', 'Roth 401(k) — Post-Tax'), ('traditional_ira', 'Traditional IRA — Pre-Tax'), ('roth_ira', 'Roth IRA — Post-Tax'), ('403b', '403(b) — Pre-Tax'), ('457', '457(b) — Pre-Tax'), ('taxable', 'Taxable Brokerage'), ('hsa', 'HSA — Triple Tax-Advantaged'), ('other_pretax', 'Other Pre-Tax'), ('other_posttax', 'Other Post-Tax')], max_length=20)),
                ('is_pre_tax', models.BooleanField(default=True, help_text='Pre-tax = contributions reduce taxable income; withdrawals taxed as ordinary income')),
                ('is_taxable', models.BooleanField(default=False, help_text='Taxable brokerage: contributions post-tax, gains taxed annually')),
                ('is_hsa', models.BooleanField(default=False)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('annual_contribution', models.DecimalField(decimal_places=2, default=0, help_text='Your annual contribution (pre-tax dollar amount)', max_digits=10)),
                ('employer_match_pct', models.DecimalField(decimal_places=2, default=0, help_text='Employer match rate %, e.g. 50 means 50 cents per dollar contributed', max_digits=5)),
                ('employer_match_limit_pct', models.DecimalField(decimal_places=2, default=0, help_text='Max % of salary employer will match, e.g. 6 means match up to 6% of salary', max_digits=5)),
                ('asset_allocation_stocks', models.DecimalField(decimal_places=2, default=80, help_text='% allocated to equities (0–100)', max_digits=5)),
                ('asset_allocation_bonds', models.DecimalField(decimal_places=2, default=20, help_text='% allocated to bonds/fixed income (0–100)', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='False = stopped contributing (old job); balance still grows')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_accounts', to='profiles.userprofile')),
            ],
            options={
                'verbose_name': 'Investment Account',
                'ordering': ['owner', 'account_type', 'name'],
            },
        ),
    ]
