# Generated by Django 5.1.15 on 2026-05-31 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomesource',
            name='ss_monthly_at_67',
        ),
        migrations.RemoveField(
            model_name='incomesource',
            name='ss_monthly_at_70',
        ),
    ]
