# Generated by Django 5.1.15 on 2026-06-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_rename_ss_monthly_at_62_to_67'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentaccount',
            name='employer_match_limit_pct',
        ),
        migrations.AlterField(
            model_name='incomesource',
            name='ss_monthly_at_67',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly SS benefit at Full Retirement Age / 67 (from SSA statement)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='investmentaccount',
            name='employer_match_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Employer contributes this % of your salary, e.g. 6 means employer adds 6% of salary per year', max_digits=5),
        ),
    ]
