# Generated by Django 5.1.15 on 2026-06-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_simplify_employer_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentaccount',
            name='employer_match_pct',
            field=models.PositiveSmallIntegerField(default=0, help_text='Employer matches this % of your contribution, e.g. 100 = dollar for dollar, 50 = 50 cents per dollar'),
        ),
    ]
