# Generated by Django 5.1.15 on 2026-06-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_employer_match_pct_to_integer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentaccount',
            name='asset_allocation_bonds',
            field=models.PositiveSmallIntegerField(default=20, help_text='% allocated to bonds/fixed income (0–100)'),
        ),
        migrations.AlterField(
            model_name='investmentaccount',
            name='asset_allocation_stocks',
            field=models.PositiveSmallIntegerField(default=80, help_text='% allocated to equities (0–100)'),
        ),
    ]
