# Generated by Django 5.1.15 on 2026-08-01 01:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_comment_is_flagged'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='flagged_by',
            field=models.ManyToManyField(blank=True, related_name='flagged_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
