# Generated by Django 5.1.15 on 2026-03-04 01:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('registration', 'User Registration'), ('invitation_sent', 'Invitation Sent'), ('password_reset', 'Password Reset Requested'), ('access_requested', 'Wishlist Access Requested'), ('access_approved', 'Wishlist Access Approved'), ('access_denied', 'Wishlist Access Denied'), ('item_added', 'Wishlist Item Added'), ('item_soft_removed', 'Item Marked No Longer Needed'), ('email_changed', 'Email Address Changed'), ('account_deleted', 'Account Deleted'), ('admin_pw_reset', 'Admin Password Reset'), ('access_reset', 'Access Request Reset by Admin')], max_length=30)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_as_actor', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_log', to='families.family')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_as_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log Entry',
                'verbose_name_plural': 'Activity Log',
                'ordering': ['-created_at'],
            },
        ),
    ]
