# Generated by Django 5.1.15 on 2026-03-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='event_type',
            field=models.CharField(choices=[('registration', 'User Registration'), ('invitation_sent', 'Invitation Sent'), ('password_reset', 'Password Reset Requested'), ('access_requested', 'Wishlist Access Requested'), ('access_approved', 'Wishlist Access Approved'), ('access_denied', 'Wishlist Access Denied'), ('item_added', 'Wishlist Item Added'), ('item_soft_removed', 'Item Marked No Longer Needed'), ('email_changed', 'Email Address Changed'), ('account_deleted', 'Account Deleted'), ('admin_pw_reset', 'Admin Password Reset'), ('access_reset', 'Access Request Reset by Admin'), ('family_created', 'Family Created by Admin'), ('family_deleted', 'Family Deleted by Admin')], max_length=30),
        ),
    ]
