# Generated by Django 5.1.15 on 2026-05-30 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_income_source_and_remove_pension_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('simulation_type', models.CharField(choices=[('deterministic', 'Deterministic'), ('monte_carlo', 'Monte Carlo')], default='deterministic', max_length=20)),
                ('expected_annual_return_stocks', models.DecimalField(decimal_places=2, default=7.0, help_text='Expected annual stock return %, e.g. 7.0', max_digits=5)),
                ('expected_annual_return_bonds', models.DecimalField(decimal_places=2, default=3.5, help_text='Expected annual bond return %, e.g. 3.5', max_digits=5)),
                ('inflation_rate', models.DecimalField(decimal_places=2, default=2.5, help_text='Annual inflation rate %, e.g. 2.5', max_digits=4)),
                ('annual_retirement_spending', models.DecimalField(decimal_places=2, default=0, help_text="Target annual spending in retirement (today's dollars)", max_digits=12)),
                ('spending_growth_rate', models.DecimalField(decimal_places=2, default=2.5, help_text='Annual spending growth % (typically = inflation)', max_digits=4)),
                ('spending_strategy', models.CharField(choices=[('fixed', 'Fixed (inflation-adjusted)'), ('percent_portfolio', '% of Portfolio (e.g. 4% rule)'), ('guardrails', 'Guardrails (reduce on downturns)')], default='fixed', max_length=20)),
                ('withdrawal_rate_pct', models.DecimalField(decimal_places=2, default=4.0, help_text='Withdrawal rate % for percent-of-portfolio strategy', max_digits=4)),
                ('mc_iterations', models.PositiveIntegerField(default=1000, help_text='Number of Monte Carlo simulation runs')),
                ('mc_confidence_level', models.PositiveSmallIntegerField(default=85, help_text='Target confidence level % (e.g. 85 = 85% of runs succeed)')),
                ('mc_return_std_dev_stocks', models.DecimalField(decimal_places=2, default=15.0, help_text='Annual stock return volatility (std dev) %, e.g. 15.0', max_digits=5)),
                ('mc_return_std_dev_bonds', models.DecimalField(decimal_places=2, default=5.0, help_text='Annual bond return volatility (std dev) %, e.g. 5.0', max_digits=5)),
                ('black_swan_enabled', models.BooleanField(default=False)),
                ('black_swan_annual_probability', models.DecimalField(decimal_places=2, default=3.0, help_text='Annual probability of a black swan event occurring, e.g. 3.0%', max_digits=5)),
                ('black_swan_min_loss_pct', models.DecimalField(decimal_places=2, default=20.0, help_text='Minimum portfolio loss % in a black swan event', max_digits=5)),
                ('black_swan_max_loss_pct', models.DecimalField(decimal_places=2, default=50.0, help_text='Maximum portfolio loss % in a black swan event', max_digits=5)),
                ('black_swan_recovery_years', models.PositiveSmallIntegerField(default=3, help_text='Average years for portfolio to recover post-event')),
                ('ss_claim_age_self', models.PositiveSmallIntegerField(default=67, help_text='Age at which you intend to claim SS benefits (62–70)')),
                ('ss_claim_age_spouse', models.PositiveSmallIntegerField(default=67, help_text='Age at which spouse intends to claim SS benefits (62–70)')),
                ('effective_tax_rate_working', models.DecimalField(decimal_places=2, default=22.0, help_text='Effective income tax rate % while working', max_digits=5)),
                ('effective_tax_rate_retirement', models.DecimalField(decimal_places=2, default=15.0, help_text='Effective tax rate % on pre-tax withdrawals in retirement', max_digits=5)),
                ('capital_gains_rate', models.DecimalField(decimal_places=2, default=15.0, help_text='Long-term capital gains tax rate % for taxable accounts', max_digits=5)),
                ('user_life_expectancy_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('spouse_life_expectancy_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='profiles.userprofile')),
            ],
            options={
                'verbose_name': 'Scenario',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('success_probability', models.DecimalField(blank=True, decimal_places=2, help_text="% of MC runs that don't exhaust the portfolio", max_digits=5, null=True)),
                ('median_balance_at_retirement', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('median_balance_at_end', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('deterministic_final_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('portfolio_exhaustion_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('result_data', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='simulations.scenario')),
            ],
            options={
                'verbose_name': 'Simulation Result',
                'ordering': ['-completed_at'],
            },
        ),
    ]
