# Generated by Django 5.1.15 on 2026-05-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='retirement_age_self',
            field=models.PositiveSmallIntegerField(default=65, help_text='Age at which you plan to retire (stops contributions, starts withdrawals)'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='retirement_age_spouse',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Age at which spouse plans to retire', null=True),
        ),
    ]
