# Generated by Django 5.1.15 on 2026-06-01 01:11

from django.db import migrations, models


def migrate_guardrails(apps, schema_editor):
    """Convert spending_strategy='guardrails' → 'fixed' + guardrails_enabled=True."""
    Scenario = apps.get_model('simulations', 'Scenario')
    Scenario.objects.filter(spending_strategy='guardrails').update(
        spending_strategy='fixed',
        guardrails_enabled=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0002_remove_retirement_age_risk_from_profile_add_to_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='guardrails_enabled',
            field=models.BooleanField(default=False, help_text='Reduce spending by 10% in any year the portfolio drops >20% below its peak'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='spending_strategy',
            field=models.CharField(choices=[('fixed', 'Fixed (inflation-adjusted)'), ('percent_portfolio', '% of Portfolio (e.g. 4% rule)')], default='fixed', max_length=20),
        ),
        migrations.RunPython(migrate_guardrails, migrations.RunPython.noop),
    ]
