# Generated by Django 5.1.15 on 2026-06-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0003_add_guardrails_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='use_smile_curve',
            field=models.BooleanField(default=False, help_text='Apply Retirement Spending Smile (spending declines in mid-retirement, rises in late retirement)'),
        ),
    ]
